# Generated by Django 6.0.2 on 2026-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
