# Generated by Django 6.0.2 on 2026-02-19 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('fare_per_person', models.PositiveIntegerField()),
                ('total_fare', models.PositiveIntegerField()),
                ('stations', models.JSONField()),
                ('distance', models.PositiveIntegerField()),
                ('interchanges', models.PositiveIntegerField()),
                ('travel_time', models.PositiveIntegerField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='CONFIRMED', max_length=20)),
            ],
        ),
    ]
