# Generated by Django 6.0.2 on 2026-02-19 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
