# Generated by Django 6.0.2 on 2026-02-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_ticket_status_paymenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.ticket'),
        ),
    ]
